/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.frames;

import core.db.entity.Bank;
import core.db.entity.User;
import core.db.impl.BankDaoImpl;
import core.db.ints.BankDao;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Rastislav,Slovenkai
 */
public class adminBankFrame extends javax.swing.JFrame
{

					private static BankDao bankDao = new BankDaoImpl();


					public void prepareTable()
					{
										DefaultTableModel tableModel = (DefaultTableModel) adminBankFrameBankTable.getModel();
										List<Bank> bankList = bankDao.getAll();
										adminBankFrameBankTable.removeAll();
										tableModel.setNumRows(bankList.size());
										int i = 0;
										for(Bank bank : bankList)
										{
															Double rating = bank.getPrimeInterestRate();
															tableModel.setValueAt(bank, i, 0);
															tableModel.setValueAt(rating, i, 1);
															i++;
										}
					}
					/**
					 * Creates new form userAdminFrame
					 */
					public adminBankFrame(User user) throws SQLException
					{
										initComponents();
										prepareTable();

					}

					/**
					 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
					 */
					@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {

          jScrollPane1 = new javax.swing.JScrollPane();
          adminBankFrameBankTable = new javax.swing.JTable();
          adminBankFrameAddBankButton = new javax.swing.JButton();
          adminBankFrameDeleteBankButton = new javax.swing.JButton();
          adminBankFrameBankNameTextField = new javax.swing.JTextField();
          menoLabel1 = new javax.swing.JLabel();
          RatingLabel1 = new javax.swing.JLabel();
          adminBankFrameRatingTextField = new javax.swing.JTextField();
          adminBankFrameChangeBankRatingFrame = new javax.swing.JButton();

          setTitle("Administrátor Správa Bánk");
          addWindowListener(new java.awt.event.WindowAdapter()
          {
               public void windowClosed(java.awt.event.WindowEvent evt)
               {
                    formWindowClosed(evt);
               }
          });

          adminBankFrameBankTable.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][]
               {
                    {null, null},
                    {null, null},
                    {null, null},
                    {null, null}
               },
               new String []
               {
                    "Meno", "Zakladna urokova sadzba"
               }
          )
          {
               Class[] types = new Class []
               {
                    Bank.class, java.lang.Double.class
               };

               public Class getColumnClass(int columnIndex)
               {
                    return types [columnIndex];
               }
          });
          jScrollPane1.setViewportView(adminBankFrameBankTable);

          adminBankFrameAddBankButton.setText("Pridať");
          adminBankFrameAddBankButton.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    adminBankFrameAddBankButtonActionPerformed(evt);
               }
          });

          adminBankFrameDeleteBankButton.setText("Odobrať");
          adminBankFrameDeleteBankButton.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    adminBankFrameDeleteBankButtonActionPerformed(evt);
               }
          });

          menoLabel1.setText("Meno");

          RatingLabel1.setText("Rating");

          adminBankFrameRatingTextField.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    adminBankFrameRatingTextFieldActionPerformed(evt);
               }
          });
          adminBankFrameRatingTextField.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyTyped(java.awt.event.KeyEvent evt)
               {
                    adminBankFrameRatingTextFieldKeyTyped(evt);
               }
          });

          adminBankFrameChangeBankRatingFrame.setText("Zmeniť úrokovú mieru označenej banky");
          adminBankFrameChangeBankRatingFrame.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    adminBankFrameChangeBankRatingFrameActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(adminBankFrameDeleteBankButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(adminBankFrameAddBankButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
                         .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(RatingLabel1)
                                   .addComponent(menoLabel1))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(adminBankFrameBankNameTextField)
                                   .addComponent(adminBankFrameRatingTextField)))
                         .addComponent(adminBankFrameChangeBankRatingFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(adminBankFrameBankNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(menoLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(adminBankFrameRatingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(RatingLabel1))
                    .addGap(18, 18, 18)
                    .addComponent(adminBankFrameAddBankButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(adminBankFrameChangeBankRatingFrame)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(adminBankFrameDeleteBankButton)
                    .addContainerGap())
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

    private void adminBankFrameAddBankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBankFrameAddBankButtonActionPerformed
									String name = adminBankFrameBankNameTextField.getText();
									String ratingText = adminBankFrameRatingTextField.getText();

									/*value is null*/
									if(name == null || ratingText == null)
														return;

									/*name is invalid lenght*/
									if(name.trim().isEmpty() || name.length() > 50)
														return;

									/*rating is empty*/
									if(ratingText.trim().isEmpty())
														return;

									try
									{
														double rating = Double.parseDouble(ratingText);
														/*all ok*/
														Bank newBank = new Bank();
														newBank.setName(name);
														newBank.setPrimeInterestRate(rating);

														bankDao.saveBank(newBank);
														prepareTable();
									}
									catch(NumberFormatException e)
									{
														return;
									}

    }//GEN-LAST:event_adminBankFrameAddBankButtonActionPerformed

    private void adminBankFrameDeleteBankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBankFrameDeleteBankButtonActionPerformed
									/*no bank selected*/
									if(adminBankFrameBankTable.getSelectedRow() == -1)
														return;
									Bank deleteBank = (Bank)adminBankFrameBankTable.getValueAt(adminBankFrameBankTable.getSelectedRow(), 0);

									if(deleteBank == null)
														return;

									/*all ok*/
									bankDao.deleteBank(deleteBank);
									prepareTable();
    }//GEN-LAST:event_adminBankFrameDeleteBankButtonActionPerformed

    private void adminBankFrameRatingTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBankFrameRatingTextFieldActionPerformed

    }//GEN-LAST:event_adminBankFrameRatingTextFieldActionPerformed


    private void adminBankFrameRatingTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminBankFrameRatingTextFieldKeyTyped
									char c = evt.getKeyChar();
									if(Character.isLetter(c) && !evt.isAltDown())
									{
														evt.consume();
									}

    }//GEN-LAST:event_adminBankFrameRatingTextFieldKeyTyped

     private void adminBankFrameChangeBankRatingFrameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_adminBankFrameChangeBankRatingFrameActionPerformed
     {//GEN-HEADEREND:event_adminBankFrameChangeBankRatingFrameActionPerformed
          
										/*no bank selected*/
									if(adminBankFrameBankTable.getSelectedRow() == -1)
														return;
									Bank bank = (Bank) adminBankFrameBankTable.getValueAt(adminBankFrameBankTable.getSelectedRow(), 0);
									if(bank == null)
														return;
									Long id = bank.getId();

									/*id is null*/
									if(id == null)
														return;
									
									/*everything ok*/
										bankSadzbaFrame sFrame = new bankSadzbaFrame(id,this);
										sFrame.setVisible(true);
						
     }//GEN-LAST:event_adminBankFrameChangeBankRatingFrameActionPerformed

     private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
     {//GEN-HEADEREND:event_formWindowClosed
         
     }//GEN-LAST:event_formWindowClosed


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel RatingLabel1;
     private javax.swing.JButton adminBankFrameAddBankButton;
     private javax.swing.JTextField adminBankFrameBankNameTextField;
     private javax.swing.JTable adminBankFrameBankTable;
     private javax.swing.JButton adminBankFrameChangeBankRatingFrame;
     private javax.swing.JButton adminBankFrameDeleteBankButton;
     private javax.swing.JTextField adminBankFrameRatingTextField;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JLabel menoLabel1;
     // End of variables declaration//GEN-END:variables
    private static Bank novaBanka;

}
