/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.frames;

import core.db.entity.User;
import core.db.entity.Bank;
import core.db.impl.BankDaoImpl;
import core.db.impl.UserDaoImpl;
import core.db.ints.BankDao;
import core.db.ints.UserDao;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rastislav, Martin
 */
public class adminUserFrame extends javax.swing.JFrame {

    private static UserDao userDao = new UserDaoImpl();
    private static BankDao bankDao = new BankDaoImpl();
    private final User user;

    /**
     * pripravi / aktualizuje tabulku pouzivatelov v systeme
     */
    public void prepareUserTable() {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        List<User> users = userDao.getAll();
        jTable1.removeAll();
        tableModel.setNumRows(users.size());
        for (int i = 0; i < users.size(); i++) {
            Long id = users.get(i).getId();
            Long idB = users.get(i).getIdB();
            String role = users.get(i).getRole();
            String meno = users.get(i).getName();
            tableModel.setValueAt(id, i, 0);
            tableModel.setValueAt(idB, i, 1);
            tableModel.setValueAt(role, i, 2);
            tableModel.setValueAt(meno, i, 3);
        }
    }

    /***
     * pripravi ComboBox pre vyber banky
     */
    private void prepareComboBox() {
        adminUserFrameBankIdComboBox.removeAll();
        adminUserFrameBankIdComboBox.removeAllItems();
        List<Bank> bankList = bankDao.getAll();
        for (Bank bank : bankList) {
            adminUserFrameBankIdComboBox.addItem(bank);
        }
    }

    /***
     * Vytvori novy adminUserFrame a pripravi prostredie
     * @param user prihlaseny uzivatel
     */
    public adminUserFrame(User user) {
        initComponents();
        prepareComboBox();
        prepareUserTable();
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        adminUserFrameAddUserButton = new javax.swing.JButton();
        adminUserFrameDeleteUserButton = new javax.swing.JButton();
        menoTextField = new javax.swing.JTextField();
        menoLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rolaLabel2 = new javax.swing.JLabel();
        rolaComboBox1 = new javax.swing.JComboBox<String>();
        adminUserFrameBankIdComboBox = new javax.swing.JComboBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "IdB", "Role", "Meno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        adminUserFrameAddUserButton.setText("Pridať");
        adminUserFrameAddUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUserFrameAddUserButtonActionPerformed(evt);
            }
        });

        adminUserFrameDeleteUserButton.setText("Odobrať");
        adminUserFrameDeleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUserFrameDeleteUserButtonActionPerformed(evt);
            }
        });

        menoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoTextFieldActionPerformed(evt);
            }
        });

        menoLabel1.setText("Meno:");

        jLabel1.setText("Banka:");

        rolaLabel2.setText("Rola:");

        rolaComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "administrator", "bank", "user" }));

        adminUserFrameBankIdComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                    .addComponent(adminUserFrameAddUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(rolaLabel2)
                            .addComponent(menoLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rolaComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminUserFrameBankIdComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menoTextField))))
                .addContainerGap())
            .addComponent(adminUserFrameDeleteUserButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menoLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rolaComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rolaLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(adminUserFrameBankIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminUserFrameAddUserButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(adminUserFrameDeleteUserButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminUserFrameDeleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUserFrameDeleteUserButtonActionPerformed

        if (jTable1.getSelectedRow() == -1) {
            return;
        }
        Long id = (Long) jTable1.getValueAt(jTable1.getSelectedRow(), 0);

        /*id is null*/
        if (id == null) {
            return;
        }

        /*I cannot delete myself*/
        if (id.equals(user.getId())) {
            return;
        }

        /*all ok*/
        userDao.deleteUser(userDao.getById(id));
        prepareUserTable();
    }//GEN-LAST:event_adminUserFrameDeleteUserButtonActionPerformed

    private void adminUserFrameAddUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUserFrameAddUserButtonActionPerformed
        String name = menoTextField.getText();
        String role = (String) rolaComboBox1.getSelectedItem();
        Bank bank = (Bank) adminUserFrameBankIdComboBox.getSelectedItem();

        /*null values*/
        if (role == null || bank == null || name == null) {
            return;
        }

        /*name lenght is incorrect*/
        if (name.trim().isEmpty() || name.length() > 24) {
            return;
        }

        /*all ok*/
        User newUser = new User();
        newUser.setIdB(bank.getId());
        newUser.setName(name);
        newUser.setRole(role);

        userDao.saveUser(newUser);
        prepareUserTable();
    }//GEN-LAST:event_adminUserFrameAddUserButtonActionPerformed

     private void menoTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menoTextFieldActionPerformed
     {//GEN-HEADEREND:event_menoTextFieldActionPerformed
         // TODO add your handling code here:
     }//GEN-LAST:event_menoTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminUserFrameAddUserButton;
    private javax.swing.JComboBox adminUserFrameBankIdComboBox;
    private javax.swing.JButton adminUserFrameDeleteUserButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel menoLabel1;
    private javax.swing.JTextField menoTextField;
    private javax.swing.JComboBox<String> rolaComboBox1;
    private javax.swing.JLabel rolaLabel2;
    // End of variables declaration//GEN-END:variables

}
