/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.frames;

import core.db.entity.BankCondition;
import core.db.entity.Condition;
import core.db.entity.Mark;
import core.db.impl.BankConditionDaoImpl;
import core.db.impl.ConditionDaoImpl;
import core.db.ints.BankConditionDao;
import core.db.ints.ConditionDao;

/**
 *
 * @author Slavomír
 */
public class bankUpdateBankConditionFrame extends javax.swing.JFrame
{
					private Long idB = null;
					private bankFrame parentFrame = null;
					private final BankCondition selectedBankCondition;
					private BankConditionDao bankConditionDao= new BankConditionDaoImpl();
					private ConditionDao conditionDao = new ConditionDaoImpl();

					/**
					 * Creates new form bankUpdateBankConditionFrame
					 */

					public bankUpdateBankConditionFrame(Long idB, bankFrame aThis,BankCondition bankCondition)
					{
									initComponents();
									this.idB = idB;
									this.parentFrame = aThis;
									this.selectedBankCondition = bankCondition;
									
									Long idC = selectedBankCondition.getIdC();
								
									Condition con = conditionDao.getById(idC);
									if(con==null)
									{
														return;
									}
								 bankUpdateBankConditionFrameDescriptionCondition.setText(con.getDescription());
								 rateTextField.setText(""+(-bankCondition.getChangeInterestRate()));
								 valueTextField.setText(""+bankCondition.getValue());
								
										bankUpdateBankConditionFrameMarkComboBox.removeAllItems();
										bankUpdateBankConditionFrameMarkComboBox.addItem(new Mark(0L, "="));
										bankUpdateBankConditionFrameMarkComboBox.addItem(new Mark(1L, ">="));
									 bankUpdateBankConditionFrameMarkComboBox.addItem(new Mark(-1L, "<="));
										bankUpdateBankConditionFrameMarkComboBox.addItem(new Mark(2L, ">"));
										bankUpdateBankConditionFrameMarkComboBox.addItem(new Mark(-2L, "<"));
										bankUpdateBankConditionFrameMarkComboBox.setSelectedIndex(0);
									
										setVisible(true);
					}
					
					
					
					/**
					 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
					 */
					@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {

          bankUpdateBankConditionFrameDescriptionCondition = new javax.swing.JLabel();
          bankUpdateBankConditionFrameMarkComboBox = new javax.swing.JComboBox();
          valueTextField = new javax.swing.JTextField();
          rateTextField = new javax.swing.JTextField();
          updateButton = new javax.swing.JButton();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();

          setTitle("Banka Upravenie Nastavenej Podmienky");

          bankUpdateBankConditionFrameDescriptionCondition.setText("popisPodmienky");

          bankUpdateBankConditionFrameMarkComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
          bankUpdateBankConditionFrameMarkComboBox.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    bankUpdateBankConditionFrameMarkComboBoxActionPerformed(evt);
               }
          });

          valueTextField.setText("500");

          rateTextField.setText("12.0");

          updateButton.setText("Zmeň");
          updateButton.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    updateButtonActionPerformed(evt);
               }
          });

          jLabel1.setText("Znamienko");

          jLabel2.setText("Hodnota");

          jLabel3.setText("Zmena úrokovej miery");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                         .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel1)
                                   .addComponent(jLabel2)
                                   .addComponent(jLabel3))
                              .addGap(19, 19, 19)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(bankUpdateBankConditionFrameDescriptionCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(bankUpdateBankConditionFrameMarkComboBox, 0, 582, Short.MAX_VALUE)
                                   .addComponent(valueTextField)
                                   .addComponent(rateTextField))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(bankUpdateBankConditionFrameDescriptionCondition)
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(bankUpdateBankConditionFrameMarkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel1))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(valueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(rateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel3))
                    .addGap(18, 18, 18)
                    .addComponent(updateButton)
                    .addContainerGap(82, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void bankUpdateBankConditionFrameMarkComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bankUpdateBankConditionFrameMarkComboBoxActionPerformed
     {//GEN-HEADEREND:event_bankUpdateBankConditionFrameMarkComboBoxActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_bankUpdateBankConditionFrameMarkComboBoxActionPerformed

     private void updateButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_updateButtonActionPerformed
     {//GEN-HEADEREND:event_updateButtonActionPerformed
         					/*no selectedCondition*/
										if(selectedBankCondition == null)
										{
															System.out.println("NO SELECTED ITEM");
															return;
										}
										String interestRateString = rateTextField.getText();
										String valueString = valueTextField.getText();

										Mark mark = (Mark) bankUpdateBankConditionFrameMarkComboBox.getSelectedItem();
									
										try
										{
															Double interestRate = Double.parseDouble(interestRateString);
															Integer value = Integer.parseInt(valueString);

															/*everything ok*/
															selectedBankCondition.setMark(mark.getId());
															selectedBankCondition.setValue(value);
															selectedBankCondition.setChangeInterestRate(-interestRate);

															bankConditionDao.updateBankCondition(selectedBankCondition);
															parentFrame.prepareBankConditionTable();
															setVisible(false);
										}
										catch(NumberFormatException e)
										{
															/*parsing error*/
															System.out.println("PARSE ERROR");
															return;
										}
     }//GEN-LAST:event_updateButtonActionPerformed

					/**
					 * @param args the command line arguments
					 */
			

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel bankUpdateBankConditionFrameDescriptionCondition;
     private javax.swing.JComboBox bankUpdateBankConditionFrameMarkComboBox;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JTextField rateTextField;
     private javax.swing.JButton updateButton;
     private javax.swing.JTextField valueTextField;
     // End of variables declaration//GEN-END:variables
}
